services:
  sshca:
    image: example/sshca
    build:
      context: ..
      dockerfile: example/Dockerfile
    ports: 
      - target: 2221
        published: 2221
        mode: host
        host_ip: 127.0.0.1
      - target: 2280
        published: 2280
        mode: host
        host_ip: 127.0.0.1
  ssh:
    image: docker.io/serversideup/docker-ssh
    ports:
      - target: 2222
        published: 2222
        mode: host
        host_ip: 127.0.0.1
    volumes:
      - type: bind
        source: ./authorized_keys
        target: /authorized_keys
      - type: volume
        source: example_ssh_host_keys
        target: /etc/ssh/ssh_host_keys/
  idp:
    image: docker.io/dexidp/dex
    ports:
      - target: 5556
        published: 5556
        mode: host
        host_ip: 127.0.0.1
    environment:
      DEX_CONNECTORS_ENABLE_MOCK: 1
volumes:
  example_ssh_host_keys:
